/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControlContractSol from "./AccessControlContract.sol";
export type { accessControlContractSol };
import type * as credentialContractSol from "./CredentialContract.sol";
export type { credentialContractSol };
export type { AuditContract } from "./AuditContract";
export type { IdentityContract } from "./IdentityContract";
export type { MockVerifier } from "./MockVerifier";
