/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CredentialContract } from "./CredentialContract";
export type { IIdentityContract } from "./IIdentityContract";
