/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIdentityContract,
  IIdentityContractInterface,
} from "../../../contracts/CredentialContract.sol/IIdentityContract";

const _abi = [
  {
    inputs: [],
    name: "ISSUER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIdentityContract__factory {
  static readonly abi = _abi;
  static createInterface(): IIdentityContractInterface {
    return new Interface(_abi) as IIdentityContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIdentityContract {
    return new Contract(address, _abi, runner) as unknown as IIdentityContract;
  }
}
