/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CredentialContract__factory } from "./CredentialContract__factory";
export { IIdentityContract__factory } from "./IIdentityContract__factory";
